INSERT INTO GENRE (GENRE_NAME) VALUES('Комедия');
INSERT INTO GENRE (GENRE_NAME) VALUES('Драма');
INSERT INTO GENRE (GENRE_NAME) VALUES('Мультфильм');
INSERT INTO GENRE (GENRE_NAME) VALUES('Триллер');
INSERT INTO GENRE (GENRE_NAME) VALUES('Документальный');
INSERT INTO GENRE (GENRE_NAME) VALUES('Боевик');

INSERT INTO MPA (MPA_NAME) VALUES('G');
INSERT INTO MPA (MPA_NAME) VALUES('PG');
INSERT INTO MPA (MPA_NAME) VALUES('PG-13');
INSERT INTO MPA (MPA_NAME) VALUES('R');
INSERT INTO MPA (MPA_NAME) VALUES('NC-17');

INSERT INTO FRIENDSHIP_STATUS (FRIENDSHIP_STATUS_ID, FRIENDSHIP_STATUS_NAME) VALUES (0, 'нет подтверждения');
INSERT INTO FRIENDSHIP_STATUS (FRIENDSHIP_STATUS_ID, FRIENDSHIP_STATUS_NAME) VALUES (1, 'дружба подтверждена');


